name: Build and deploy Python project to Azure Function App - vat-dfunc-v1

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: '3.10'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: 'Deploy to Azure Functions'
        uses: Azure/functions-action@v1
        with:
          app-name: 'vat-dfunc-v1'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_DBA70988978849A8B7A18883AA7DDBAB }}
          package: '.'
